project_name: binocs
builds:
  - id: binocs
    binary: binocs
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
  - id: binocs-macos
    binary: binocs
    goos:
      - darwin
    goarch:
      - amd64
      # - arm64
    hooks:
      post: gon -log-level=debug -log-json gon.json
archives:
  - format: binary
checksum:
  algorithm: sha256
# signs:
#   - signature: "${artifact}.dmg"
#     artifacts: all
#     ids:
#       - binocs-macos
#     cmd: gon
#     args:
#       - -log-level=debug
#       - -log-json
#       - gon.json
    # env:
    #   - AC_PASSWORD={{ .Env.AC_PASSWORD }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
