project_name: binocs
builds:
  - id: binocs-linux
    binary: binocs
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    goamd64:
      - v1
  - id: binocs-windows
    binary: binocs
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    goamd64:
      - v1
  - id: binocs-macos-amd64
    binary: binocs
    goos:
      - darwin
    goarch:
      - amd64
    goamd64:
      - v1
    hooks:
      post:
       - cmd: 'gon -log-level=info -log-json gon.amd64.json'
         output: true
  - id: binocs-macos-arm64
    binary: binocs
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
       - cmd: 'gon -log-level=info -log-json gon.arm64.json'
         output: true
archives:
  - format: binary
checksum:
  algorithm: sha256
changelog:
  sort: asc
nfpms:
  -
    id: binocs
    package_name: binocs
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - binocs-linux
    vendor: Binocs
    homepage: https://binocs.sh/
    maintainer: Jaroslav Holub <jaroslav@binocs.sh>
    description: |-
      Binocs is a CLI-first uptime and performance monitoring tool for websites, applications and APIs.
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    rpm:
      group: Unspecified
      compression: gzip
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    # apk:
    