project_name: binocs
builds:
  - id: binocs
    binary: binocs
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
  - id: binocs-macos
    binary: binocs
    goos:
      - darwin
    goarch:
      - amd64
      # - arm64
    # hooks:
    #   post: gon gon.json
archives:
  - format: binary
checksum:
  algorithm: sha256
signs:
  - signature: "${artifact}"
    artifacts: all
    ids:
      - binocs-macos
    cmd: gon
    args:
      - gon.json
    # env:
    #   - AC_PASSWORD={{ .Env.AC_PASSWORD }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
