project_name: binocs
builds:
  # - id: binocs
  #   binary: binocs
  #   goos:
  #     - linux
  #     - windows
  #   goarch:
  #     - 386
  #     - amd64
  #     - arm64
  - id: binocs-macos-amd64
    binary: binocs
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
       - cmd: 'gon -log-level=debug -log-json gon.amd64.json'
         output: true
  - id: binocs-macos-arm64
    binary: binocs
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
       - cmd: 'gon -log-level=debug -log-json gon.arm64.json'
         output: true
archives:
  - format: binary
checksum:
  algorithm: sha256
changelog:
  sort: asc
