project_name: binocs
builds:
  - id: binocs
    binary: binocs
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
  - id: binocs-macos
    binary: binocs
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
       - cmd: 'gon -log-level=debug -log-json gon.json'
         output: true
         env:
          - BINOCS_SOURCE_FILE_PATH="{{ .Path }}"
          - BINOCS_OUTPUT_ZIP_FILE_PATH="{{ .Path }}.zip"
archives:
  - format: binary
checksum:
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
