name: Build Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Import certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Install gon via homebrew
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.12.2
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          APPLE_ID_AC_PASSWORD: ${{ secrets.APPLE_ID_AC_PASSWORD }}
